 # Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true
scan_timeout = 200
command_timeout = 1000

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$fill\
$git_commit\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$line_break\
$character"""

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = "[\uf0a9](bold green)" # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = "[\uf0a9](bold purple)"

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = false

[nodejs]
format = "[\ued0d \ue628 ](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

[golang]
format = "[\ue627 ](bold cyan) "

[lua]
format = "[\ue620 ](bold blue) "

[localip]
ssh_only = true
format = '@[$localipv4](bold red) '
disabled = false

[git_branch]
format = "[$symbol$branch(:remote_branch) ](purple)"

[git_commit]
only_detached = false
tag_disabled = false

[git_metrics]
disabled = false

[git_status]
ahead = "[⇡$count](green)"
diverged = "[⇕](purple)[⇡$ahead_count](green)[⇣$behind_count](yellow)"
behind = "[⇣$count](yellow)"
conflicted = "[!=](red)"
style = 'bold green'

[time]
disabled = false
format = "[$time ]($style)"

[docker_context]
format = "[\uf308 ](blue)"

[python]
format = "[\ue73c ](bold yellow)"

[rust]
format = "[\ue7a8 ](bold red)"

[shell]
disabled = false

[php]
format = "[\ue73d ](bold blue)"

[cmd_duration]
min_time = 50
show_milliseconds = true
